### ISSUE TITLE
你好，咨询一个im 会话问题

### ISSUE THREAD

**Issue by lucky-lbc** [Binx98/QuickChat#102]
1. 我在写im 过程中，有个会话疑问
场景： 服务保存会话，采用redis 存储，当前用户会话id, 消息时间，进行排序
问题：3000人的群，发一条消息，会话如何更新，3000人会话全部更新，有啥更好的解决方式吗?

**Comment by Binx98** [comment]
1. 从业务角度来看，微信也不过用了500人群，可以可以的话完全可以妥协，减少最大群成员
2. 既然会话缓存频繁改动，是否可以考虑不通过redis缓存，不使用缓存是否可以满足性能要求

**Comment by lucky-lbc** [comment]
> 1. 从业务角度来看，微信也不过用了500人群，可以可以的话完全可以妥协，减少最大群成员
> 
>     2. 既然会话缓存频繁改动，是否可以考虑不通过redis缓存，不使用缓存是否可以满足性能要求

嗯嗯，感觉放redis 搞不了。先放MySQL，有个批量添加。
我现在有第二个问题，离线消息，历史消息是一个事吗，比如 mysql 设计表是读扩散，离线消息也是读mysql ，还是两个是分开得呢，离线写扩散到缓存，

**Comment by Binx98** [comment]
离线消息这个概念我没有细致了解过，我的项目中没牵扯这块逻辑，都是存储到mysql和redis，进行读写操作的。我是没有分开的
